name: GrapeDB CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Latest GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-13 cmake
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Tests
      run: ./${{github.workspace}}/build/grapedb_tests