name: GrapeDB CI (C++23 Ready)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up GCC 14
      run: |
        sudo apt update
        sudo apt install -y g++-14
        # Встановлюємо пріоритет для GCC 14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14
        sudo update-alternatives --set gcc /usr/bin/gcc-14

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-14

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: ./build/grapedb_tests